### ISSUE TITLE
Concepts?

### ISSUE THREAD

**Issue by marcelklehr** [MaddieM4/ConcurrenTree#39] opened 2013-09-03 18:15 UTC
hey there,

I'm intrigued. I know OT fairly well and all the rambling about it and how ctree is so much better let's me want to check out the concepts behind ctree.

But I can't find any enlightening explanations of how ctree woks exactly. Could you help me out here?

**Comment by MaddieM4** [comment] 2013-09-04 16:53
Heh, hope the rambling didn't offend you too badly! CTree was born out of my frustration with OT, and it shows in a lot of ways, one of which is the frequent comparisons between the two. CTree gets its value, in a high-level sense, by giving the data additional structure, which is less memory-efficient than OT, but opens up a lot of benefits, especially for distributed applications (most importantly, and this is probably founded in my own somewhat antisocial nature, that you should never have to state-track another participant).

I am not actively working on CTree at the moment, and the code is very dusty. There's one large section in particular, the network protocol, which I intend to completely rip out when I get back into CTree development. However, this is not a dead project, merely on-hold pending even bigger things. See this blog entry for more information:

http://roaming-initiative.com/blog/blog/what-about-ctree.html

(Note that the blog post above is seriously simplified for the layperson, and often a bit editorial. The explanation below should be a bit more technical, and more professional in tone).

## Strings

It's not terribly complicated if you're only dealing with strings, and the same principles found the more complicated data types, so I always like to start with an explanation of how strings work. You may be surprised how truly simple it is.

In CTree, all strings are immutable. If you want to modify the way a string is presented, you have two methods available to you - deletion and insertion.

## Deletion

A CTree string object has not only an array of characters, but an array of boolean values, one for each character. If the boolean value for a character is _True_, the character is displayed. If the boolean value for a character is _False_, the character is not displayed.

I learned after implementing this that I'd reinvented an existing technique, more commonly known as tombstoning.

## Insertion

Every "edge" between characters, and on each end of the string, has an initially-empty set of child strings. These child strings are also full CTree string objects, which is where you get the tree structure. When a CTree string is "rendered" to a flat Python string (or whatever native string type in your language of choice), every edge is rendered as the concatenation of all the child strings, where the child strings are sorted in a deterministic order based only on their "keys", which are in turn based on that child string's initial, immutable value.

The key-calculation algorithm is somewhat arbitrary, intended to be quick in simple cases, while still reliably differentiating long strings with common prefix text. It consists of up to 10 characters of verbatim string contents, after which, if there are any remaining characters, these remaining characters are hashed with a cryptographic hashing algorithm, and the hex digest of the hash is appended to the key. This saves a hashing operation for determining the key of a string with less than 10 characters, which is very handy for applications that have many small insertions, such as live typing.

The design is not for people to _intentionally_ introduce multiple strings into a single child-set - it's good form to always traverse deeper into the tree when you would otherwise insert into a contested edge. This is simply a mechanism for making the best of collisions, in an eventual-consistency paradigm.

## Node addressing

A node may be addressed with a list, indicating the traversal necessary to get from the root node to the intended node. For example, an empty list `[]` would be the address of the root node. Each traversal is given as `[position, key]`, where position is the optional edge ID (by default, the last edge in the currently traversed node), and key is the precalculated key of the intended child node within that edge. See the Insertion section for more information on how keys are calculated for CTree strings.

Example address: `[8,"rt", "samwise"]`

Would first go to Edge 8 of the root node, and find the child with the key "rt". From there, it would look in the "rt" node's final edge, for a node with a key of "samwise".

## Instructions

An instruction invokes some small idempotent action on the tree node at the given address. It is a list consisting of an instruction code, an address, and instruction-specific parameters.

Delete (tombstone) char 3 from root node: `[0,[],3]`
Delete chars 5-7, as well as 9, from root node: `[0,[],[5-7],9]`
Delete char 2 from child node: `[0,[8," bbrave"],2]`

Insert child node into root node at edge 7: `[1,[],7," and cherish them always."]`
Insert a child node deeper in the structure: `[1,["lm",1,"a"],0,"A"]`

Yes, every single instruction is idempotent and atomic. Deletion succeeds, even if it tombstones already-tombstoned values. Insertion does nothing if an equivalent node has already been inserted. And if the address is invalid (or the instruction is invalid in some other way) it will fail without affecting the tree.

## Operations

An operation is a bundle of ordered instructions, to be applied transactionally to the tree. If any instruction fails, the whole operation is rolled back. 

Operation failure does not necessarily mean that the operation is _invalid_, it may simply be operating on a piece of structure that other people know about, and you don't. For example, let's say that Op A lays the groundwork for Op B. If you get Op B before Op A, it will fail, but it will get put in a "failure queue." Then when you get Op A, it will apply successfully, which will trigger the reattempting of everything in the failure queue, which means Op B will succeed and be removed from the queue. Reattempts continue until the queue is either empty, or unchanged since the start of the reattempt cycle (no successes).

This is _designed_ to support making sense of a world where operations can come to your process in any wonky order, without anyone else have to give a rip about tracking your document state. If it works, it works; if not, we can try it again later. It's very freeing when every change-set you may get or make is both idempotent (regardless of personal state) and transactional.

## Flattening

The one truly unique downside of CTree is its need for occasional maintenance. Because the tree structure forms a sloppy sort of historical record of the document, a document can have a fairly small representation, but a fairly large memory footprint (for example, several hours of live-typing, trimmed down significantly afterwards, leaving tombstoned immutable data all over the place). Given this, it will be useful in may cases to periodically flatten the CTree structure to its simplest representation. For strings, this means flattening the entire tree down into a single new root node.

Flattening has consequences. Operations tailored to the old tree structure will no longer be valid, because that structure has been intentionally blown away. Furthermore, an operation may be "accidentally valid", for example, a delete of root's character 0 will always be valid as long as the root string is one character or longer, but it may not have the intended effect in the fresh tree if it was intended for the old one. Or vice-versa, for that matter.

So the complexity of flattening is not actually in the basic process, which is actually quite fundamental to the use of CTree for the rendering of representation values (you're always going to show the user a flattened version of the structure anyways). The complexity is in synchronizing the flattening process among multiple peers in an eventual consistency environment. In general, the system is designed such that you can _email operations from person to person,_ and they will still have their intended effects even if applied in a strange order weeks later, but the one exception to this otherwise glorious leniency is flattening synchronization.

For most of the development process, CTree had its own protocol, of one sort or another, and one of the things I was having a terrible time solving was the flattening sync problem. [Since temporarily abandoning CTree to work on other projects](http://roaming-initiative.com/blog/blog/what-about-ctree.html), I've come to the conclusion that a network protocol is actually outside the scope of CTree itself, and that the problem of flattening sync (and network communication in general) is one that should be the responsibility of the application.

# In conclusion

CTree, like a high-level language, trades off some CPU time and memory in return for being significantly easier to reason about, especially in massive-latency decentralized applications. It is actually likely to be more resource-efficient than OT for some specific applications due to its total lack of state tracking (I am here thinking about Google Wave's early days, though that slowness cannot be completely blamed on OT).

It is currently on hold while I work on another concurrency engine, DEJE, which has different goals and properties, and will theoretically make a great wrapper for CTree objects, solving the flattening sync problem. The long-term goal is to stress-test this combination with Orchard, a Google/Apache Wave successor that operates in a completely decentralized manner, without requiring centralized federation.

**Comment by marcelklehr** [comment] 2013-09-04 19:05
First up: That was a thorough, sensational, satisfactory explanation!
So, thanks for that. :)

the concept is pretty straightforward.. It's like ctree is the other
side of the coin. OT stores mutations and transforms against them to be
applicable on a flat string, while ctree applies mutations onto mutations.

So.. What about Tree-like data sturctures, like JSON?

**Comment by MaddieM4** [comment] 2013-09-04 19:24
> First up: That was a thorough, sensational, satisfactory explanation!
> So, thanks for that. :)

Aww, shucks :)

> the concept is pretty straightforward.. It's like ctree is the other
> side of the coin. OT stores mutations and transforms against them to be
> applicable on a flat string, while ctree applies mutations onto mutations.

That's a pretty good way of looking at it. You start with a flat value, and accumulate mutations on top of it.

> So.. What about Tree-like data sturctures, like JSON?

Oh, now that's where things get interesting, special-case-y, and complicated. I'd be happy to do a similar write-up on how they work, but it's going to need to wait a bit, as the workload at my day job has just significantly picked up post-lunch-break. Will post in awhile.

**Comment by MaddieM4** [comment] 2013-09-06 06:40
# Non-String CTree datatypes

CTree has extra classes that make it possible to represent any JSON structure in a concurrently-editable format. These "nodes" don't actually don't match 1:1 with JSON types, as we'll see later. These use the same delete instruction code (0) as strings, but each node type has a different insertion instruction code. For example, 1 = insert string, 2 = insert map, etc.

These will be presented in order of their instruction value, but that may not be the simplest order to read and understand them. The Trinary and Number nodes are the most self-contained and easy to understand. After that it gets container-y, and you basically have to understand Single nodes (their purpose and use) to understand the container types.

## String node

Just a quick note here - I lied earlier for the sake of simplicity. The key algorithm is the same as I said before, but it's run on `'t' + self._value`, not just `self._value`, so that there are no key collisions with other node types (in fact, you can always tell a node's type by its key, though this property is never really used for anything). So the key for a String node with immutable value "joe" would be "tjoe", and for a longer string, something like "tsomelonge782BC9SOMEHASH982989..." (I'm not actually gonna bother to hash that).

## Map node

A JSON object, {}.

Map nodes have a tricky problem, in that the word "key" is completely overloaded with meanings. There are node keys, as in, the node's "key" property (recall the key property for the string node). There are the keys of the actual JSON map you're representing. And there are "limit keys", which restrict a map key to only contain nodes with a specific node key.

The CTree access/traversal model considers each node to have edges/child sets that are addressable as a (pos, key) pair. For most types, pos is an integer number. For Map nodes, they are a string - the map key. The second element is always "/single", because every value within a Map node is stored within a Single node. For this reason, the position is _required_ when addressing map values, unlike String nodes, which can infer a missing position argument based on the length of the String node's immutable value.

A Map node's immutable value is actually a "limit set", a {key:value} object that defines the limit keys of the node. This is basically optional, as you can pass in an empty object if you don't care about limit keys, however, this is how Map nodes are "told apart from each other" in terms of idempotence and adressing (see key calculation below, which is entirely based on the limit dict).

Deletion is not supported by Map nodes. Because of idempotence, if you delete a map key, you can never set anything else to it later (well, you can set it, but it'll just be ignored when creating a flattened output representation). Conceptually, all we really _want_ is the ability to set the value for a key. Right now we treat None as a "key is absent" value, but that's bad, and really, when I get back into development, I need to add an Absent node to represent "no value at all".

Key is `keysum(strict(limitdict))`, where `keysum` is that key algorithm from earlier, and `strict` is a fairly simple strict JSON serialization that sorts object keys and doesn't use any whitespace.

```
[2, [...], {}] # Insert Map node with no limit keys
[2, [...], {"Hello, world" : "/true"}] # Insert Map node where the value for "Hello World" must always be True
[6, [..., "Hello, world", "/single"], true] # Actually set the value for map key "Hello World"
```

## List node

A JSON list, [].

A list is in some ways conceptually similar to a map. Its key is based on its initial limit set, although in this case, that is an array of key values. Actually, it's a bit more complex than that - a limit set can contain ints, which signal "skips" for values where you don't limit the node key of the content. A quick example here is the best way I can show what I mean:

```
["tsmall", "tmedium", "tlarge"] # List that can only possibly hold values ["small", "medium", "large"]
["tfirst", 8, "tlast"] # List where we specify the keys for either end, but indicate 8 slots in the middle that can be any value.
[1, "tsomething", 2, "tanother"] # Key limits and skips can be used back and forth
[200] # You can simply define a length, and not limit any keys at all!
```

By now, you may be seeing the usefulness of limit sets. While you can make a container without a limit set and immediately fill it in without too much collision worry (by doing all those instructions within a single operation), the limit set is what the defines the unique "soul" of a container in terms of idempotence, identification, and edge competition, because the limit set is what the key is made from.

A List has some similarities to a String as well, which mostly helps to point out the challenges of representing a List in CTree. A String, for example, is made of immutable characters, whereas a List's initial content is a set of Single nodes. And of course, we need to be able to insert new elements as well. So how _do_ we represent this?

First of all, we have a child set for every deletable position in the list, and a child set for every edge between positions. The child sets for positions can only contain Single nodes, and are ignored for rendering purposes if marked deleted (tombstoned). The child sets for edges can only contain List nodes, and behave a bit like child String nodes - the value of an edge is the concatenation of every List within the edge, where those Lists are sorted by key. So for example, if I have a List ["hello", "world"] and insert List ["crazy"] into its Edge 1 (zero-indexed), the rendered value of that parent list would be ["hello", "crazy", "world"]. The edge list is not nested.

Now, in terms of indexing, there's basically just this one big array of child sets, containing both positions and edges. The positions are first (0 to len(List)-1), the edges are everything after that (len(List) to len(List)*2 +1). Remember, there are len(List) +1 edges:

```
 | item0 | item1 | item2 |

3 items, 3 + 1 = 4 edges, 3+4 = 3*2+1 = 7 total child sets
```

So you can access any item Single node, or any edge sub-List, via a single address resolution step, given the classic (pos, key) pair. Because the List length is calculated as the number of items according to the limit set (and not self.biglength, which includes the number of edges), it's rarely useful to leave off the optional position when addressing subnodes of a list, since it's not useful for extending the end of the list, only accessing the last position item.

Because positional items can be deleted and the list can be extended from any edge, limit sets do not actually limit the rendered representation of a List. You might end up deleting all the original values and replace it all with sub-Lists, in a way reminiscent of [the Zombie Axe Conundrum](http://36chambers.wordpress.com/2007/03/30/a-philosophical-conundrum/) (also known as the Ship of Theseus or Thesus' paradox), but from an implementation/protocol perspective, we can actually say with surety that it's the same list, because of the path with which we access and change it (in this way, CTree is very handy about creating and enforcing distinctions between things that render the same, but have different "provenance", which takes the air out of a lot of philosophical problems in a way that only an engineer can).

Key is `keysum(strict(self.limitlist))` (see Map.key explanation)

```
[3, [...], 8, [4]] # Insert a List node with four deletable positional items, no key limits, at position 8
[3, [...], ["tready", "tsteady", "tgo"], 8] # Insert a list with values restricted to ["ready", "steady", "go"] at pos 8
[5, [..., "[\"tready\"829898hashstuff" ], 0 ] # Insert Single node at position 0 of list
[1, [..., "[\"tready\"829898hashstuff", 0, "/single"], 0, "ready"] # Insert actual "ready" String node into Single node
[3, [..., "[\"tready\"829898hashstuff" ], 3, [5]] # At first edge (Edge 0 == childset 3) extend list with sub-list 5 elements long
```

## Number node

A JSON number. For concurrency reasons, each Number node is composed of two components - the value, and the "unique". The value part is pretty straightforward, but why do we need a pseudo-random number tacked on with it?

Well, the reason is, numbers are designed to be iteration-friendly and collision-safe. For this reason, Number nodes actually have a slot for children! The flattened value of a Number node is its original immutable value, plus the sum of the flat values of its children.

Further, imagine if multiple people try to increment something at once. Without a unique number, the two actions would be treated as one, because thanks to the idempotence properties of CTree, it would just seem like the same action applied multiple times. Therefore, to keep the actions distinct, we give each node a random unique number, which does not affect the node value, but makes it easier to reason about child deltas.

Key is `"n" + str(int(value)) + str(unique)`

```
# value may be given as a string or actual number
# unique is always an int
[4, [...], "124.1", 8028667] # Insert value of 124.1, with unique 8028667
[4, [...], 124.1, 8028667] # Take your chances with floating point
[4, [...], 9, 7739279] # Regular old int
```

## Single node

Container for a single JSON object. Has no actual JSON equivalent. Used by the container classes.

A Single node has two edges - one for actual child, one for "replacement" that only accepts other Single nodes. Single nodes always have the key "/single". In a String node, where there is competition, there is concatenation determined by key sort. In a Single node, for the child value, only the competing child with the highest key is used - however, if any replacement Single node is present in the replacement edge, its flat value is returned instead. This is intended to ensure that _the most knowledgeable value wins._

They are used to wrap the contents of container nodes, which abstracts the replacement and single-value-enforcement code. They also help to simplify addressing, as I recall, but it's been a heck of a long time since I was in this code. Another interesting feature, used by the containers, is that you can optionally limit them to only accept child nodes with a specific key.

Key is always "/single"

```
[5, [...], 2] # Insert a Single node at position 2
```

## Trinary node

May be True, False, or None.

Key will be "/true", "/false", or "/null", accordingly.

```
[6, [...], true] # Insert a True value at the given address.
[6, [...], null] # Insert a None value at the given address
```

---

Sorry it took so long to get back to you on that, but as you can see, there was a serious ton of stuff to write, and as you can imagine, I had to do a lot of refresh-memory-from-source on this one, that I didn't have to do for the more basic stuff earlier. Which hasn't aged as badly as [some other projects](https://github.com/campadrenalin/python-libdeje), although CTree definitely has some cringeworthy corners that will need smoothing out - mostly in terms of variable naming and readability, which is sad, since ultimately the source is the Most Accurate Documentation any software can have.

Anyways, I hope that helps, or at least drops a ton of Things To Think About on you :)

**Comment by MaddieM4** [comment] 2013-09-20 23:18
I'm going to close this for now since it's not actually an issue. See #41 for a future simplification of the above information (which, like all changes to this codebase, are pending me getting other stuff sorted first).

**Closed as completed by MaddieM4** 2013-09-20 23:18 UTC
